language: ruby
sudo: false
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/csv_9.0.gemfile
  - gemfiles/csv_10.0.gemfile
  - gemfiles/csv_11.0.gemfile
  - gemfiles/simple_form_3.5.gemfile
  - gemfiles/simple_form_4.0.gemfile
